/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IERC20Permit__factory } from "./IERC20Permit__factory";
export { TreasuryPool__factory } from "./TreasuryPool__factory";
