/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface TreasuryPoolInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "adjustBalance"
      | "calculateCost"
      | "deductBalance"
      | "deductFlockCost"
      | "emergencyWithdraw"
      | "flockCostPerCall"
      | "flockWallet"
      | "getBalance"
      | "getCallCount"
      | "getTotalFlockPayments"
      | "getTotalPaid"
      | "getTreasuryBalance"
      | "owner"
      | "receivePayment"
      | "receivePaymentWithPermit"
      | "renounceOwnership"
      | "setFlockCost"
      | "setFlockWallet"
      | "setTreasuryAdmin"
      | "totalFlockPayments"
      | "totalTreasuryBalance"
      | "transferOwnership"
      | "treasuryAdmin"
      | "usdc"
      | "userBalances"
      | "userCallCount"
      | "userTotalPaid"
      | "withdrawUSDC"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "BalanceWithdrawn"
      | "FlockCostUpdated"
      | "FlockPaymentMade"
      | "FlockWalletUpdated"
      | "OwnershipTransferred"
      | "PaymentReceived"
      | "PermitPayment"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "adjustBalance",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "calculateCost",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "deductBalance",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "deductFlockCost",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "emergencyWithdraw",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "flockCostPerCall",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "flockWallet",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getBalance",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getCallCount",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getTotalFlockPayments",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getTotalPaid",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getTreasuryBalance",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "receivePayment",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "receivePaymentWithPermit",
    values: [
      AddressLike,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BytesLike,
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setFlockCost",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setFlockWallet",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setTreasuryAdmin",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "totalFlockPayments",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalTreasuryBalance",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "treasuryAdmin",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "usdc", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "userBalances",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "userCallCount",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "userTotalPaid",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawUSDC",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "adjustBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "calculateCost",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "deductBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "deductFlockCost",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "emergencyWithdraw",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "flockCostPerCall",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "flockWallet",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getBalance", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getCallCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTotalFlockPayments",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTotalPaid",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTreasuryBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "receivePayment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "receivePaymentWithPermit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setFlockCost",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setFlockWallet",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setTreasuryAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalFlockPayments",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalTreasuryBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "treasuryAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "usdc", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "userBalances",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "userCallCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "userTotalPaid",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawUSDC",
    data: BytesLike
  ): Result;
}

export namespace BalanceWithdrawnEvent {
  export type InputTuple = [
    to: AddressLike,
    amount: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [to: string, amount: bigint, timestamp: bigint];
  export interface OutputObject {
    to: string;
    amount: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FlockCostUpdatedEvent {
  export type InputTuple = [newCost: BigNumberish];
  export type OutputTuple = [newCost: bigint];
  export interface OutputObject {
    newCost: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FlockPaymentMadeEvent {
  export type InputTuple = [
    user: AddressLike,
    amount: BigNumberish,
    callCount: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    user: string,
    amount: bigint,
    callCount: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    user: string;
    amount: bigint;
    callCount: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FlockWalletUpdatedEvent {
  export type InputTuple = [newWallet: AddressLike];
  export type OutputTuple = [newWallet: string];
  export interface OutputObject {
    newWallet: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PaymentReceivedEvent {
  export type InputTuple = [
    user: AddressLike,
    amount: BigNumberish,
    timestamp: BigNumberish,
    reason: string
  ];
  export type OutputTuple = [
    user: string,
    amount: bigint,
    timestamp: bigint,
    reason: string
  ];
  export interface OutputObject {
    user: string;
    amount: bigint;
    timestamp: bigint;
    reason: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PermitPaymentEvent {
  export type InputTuple = [
    user: AddressLike,
    amount: BigNumberish,
    deadline: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    user: string,
    amount: bigint,
    deadline: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    user: string;
    amount: bigint;
    deadline: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface TreasuryPool extends BaseContract {
  connect(runner?: ContractRunner | null): TreasuryPool;
  waitForDeployment(): Promise<this>;

  interface: TreasuryPoolInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  adjustBalance: TypedContractMethod<
    [user: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  calculateCost: TypedContractMethod<
    [callCount: BigNumberish],
    [bigint],
    "view"
  >;

  deductBalance: TypedContractMethod<
    [user: AddressLike, amount: BigNumberish],
    [boolean],
    "nonpayable"
  >;

  deductFlockCost: TypedContractMethod<
    [user: AddressLike, callCount: BigNumberish],
    [boolean],
    "nonpayable"
  >;

  emergencyWithdraw: TypedContractMethod<[], [void], "nonpayable">;

  flockCostPerCall: TypedContractMethod<[], [bigint], "view">;

  flockWallet: TypedContractMethod<[], [string], "view">;

  getBalance: TypedContractMethod<[user: AddressLike], [bigint], "view">;

  getCallCount: TypedContractMethod<[user: AddressLike], [bigint], "view">;

  getTotalFlockPayments: TypedContractMethod<[], [bigint], "view">;

  getTotalPaid: TypedContractMethod<[user: AddressLike], [bigint], "view">;

  getTreasuryBalance: TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  receivePayment: TypedContractMethod<
    [user: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  receivePaymentWithPermit: TypedContractMethod<
    [
      user: AddressLike,
      amount: BigNumberish,
      deadline: BigNumberish,
      v: BigNumberish,
      r: BytesLike,
      s: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setFlockCost: TypedContractMethod<
    [newCost: BigNumberish],
    [void],
    "nonpayable"
  >;

  setFlockWallet: TypedContractMethod<
    [newWallet: AddressLike],
    [void],
    "nonpayable"
  >;

  setTreasuryAdmin: TypedContractMethod<
    [newAdmin: AddressLike],
    [void],
    "nonpayable"
  >;

  totalFlockPayments: TypedContractMethod<[], [bigint], "view">;

  totalTreasuryBalance: TypedContractMethod<[], [bigint], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  treasuryAdmin: TypedContractMethod<[], [string], "view">;

  usdc: TypedContractMethod<[], [string], "view">;

  userBalances: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  userCallCount: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  userTotalPaid: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  withdrawUSDC: TypedContractMethod<
    [amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "adjustBalance"
  ): TypedContractMethod<
    [user: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "calculateCost"
  ): TypedContractMethod<[callCount: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "deductBalance"
  ): TypedContractMethod<
    [user: AddressLike, amount: BigNumberish],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "deductFlockCost"
  ): TypedContractMethod<
    [user: AddressLike, callCount: BigNumberish],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "emergencyWithdraw"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "flockCostPerCall"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "flockWallet"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getBalance"
  ): TypedContractMethod<[user: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getCallCount"
  ): TypedContractMethod<[user: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getTotalFlockPayments"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getTotalPaid"
  ): TypedContractMethod<[user: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getTreasuryBalance"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "receivePayment"
  ): TypedContractMethod<
    [user: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "receivePaymentWithPermit"
  ): TypedContractMethod<
    [
      user: AddressLike,
      amount: BigNumberish,
      deadline: BigNumberish,
      v: BigNumberish,
      r: BytesLike,
      s: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setFlockCost"
  ): TypedContractMethod<[newCost: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setFlockWallet"
  ): TypedContractMethod<[newWallet: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setTreasuryAdmin"
  ): TypedContractMethod<[newAdmin: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "totalFlockPayments"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalTreasuryBalance"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "treasuryAdmin"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "usdc"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "userBalances"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "userCallCount"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "userTotalPaid"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "withdrawUSDC"
  ): TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;

  getEvent(
    key: "BalanceWithdrawn"
  ): TypedContractEvent<
    BalanceWithdrawnEvent.InputTuple,
    BalanceWithdrawnEvent.OutputTuple,
    BalanceWithdrawnEvent.OutputObject
  >;
  getEvent(
    key: "FlockCostUpdated"
  ): TypedContractEvent<
    FlockCostUpdatedEvent.InputTuple,
    FlockCostUpdatedEvent.OutputTuple,
    FlockCostUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "FlockPaymentMade"
  ): TypedContractEvent<
    FlockPaymentMadeEvent.InputTuple,
    FlockPaymentMadeEvent.OutputTuple,
    FlockPaymentMadeEvent.OutputObject
  >;
  getEvent(
    key: "FlockWalletUpdated"
  ): TypedContractEvent<
    FlockWalletUpdatedEvent.InputTuple,
    FlockWalletUpdatedEvent.OutputTuple,
    FlockWalletUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "PaymentReceived"
  ): TypedContractEvent<
    PaymentReceivedEvent.InputTuple,
    PaymentReceivedEvent.OutputTuple,
    PaymentReceivedEvent.OutputObject
  >;
  getEvent(
    key: "PermitPayment"
  ): TypedContractEvent<
    PermitPaymentEvent.InputTuple,
    PermitPaymentEvent.OutputTuple,
    PermitPaymentEvent.OutputObject
  >;

  filters: {
    "BalanceWithdrawn(address,uint256,uint256)": TypedContractEvent<
      BalanceWithdrawnEvent.InputTuple,
      BalanceWithdrawnEvent.OutputTuple,
      BalanceWithdrawnEvent.OutputObject
    >;
    BalanceWithdrawn: TypedContractEvent<
      BalanceWithdrawnEvent.InputTuple,
      BalanceWithdrawnEvent.OutputTuple,
      BalanceWithdrawnEvent.OutputObject
    >;

    "FlockCostUpdated(uint256)": TypedContractEvent<
      FlockCostUpdatedEvent.InputTuple,
      FlockCostUpdatedEvent.OutputTuple,
      FlockCostUpdatedEvent.OutputObject
    >;
    FlockCostUpdated: TypedContractEvent<
      FlockCostUpdatedEvent.InputTuple,
      FlockCostUpdatedEvent.OutputTuple,
      FlockCostUpdatedEvent.OutputObject
    >;

    "FlockPaymentMade(address,uint256,uint256,uint256)": TypedContractEvent<
      FlockPaymentMadeEvent.InputTuple,
      FlockPaymentMadeEvent.OutputTuple,
      FlockPaymentMadeEvent.OutputObject
    >;
    FlockPaymentMade: TypedContractEvent<
      FlockPaymentMadeEvent.InputTuple,
      FlockPaymentMadeEvent.OutputTuple,
      FlockPaymentMadeEvent.OutputObject
    >;

    "FlockWalletUpdated(address)": TypedContractEvent<
      FlockWalletUpdatedEvent.InputTuple,
      FlockWalletUpdatedEvent.OutputTuple,
      FlockWalletUpdatedEvent.OutputObject
    >;
    FlockWalletUpdated: TypedContractEvent<
      FlockWalletUpdatedEvent.InputTuple,
      FlockWalletUpdatedEvent.OutputTuple,
      FlockWalletUpdatedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "PaymentReceived(address,uint256,uint256,string)": TypedContractEvent<
      PaymentReceivedEvent.InputTuple,
      PaymentReceivedEvent.OutputTuple,
      PaymentReceivedEvent.OutputObject
    >;
    PaymentReceived: TypedContractEvent<
      PaymentReceivedEvent.InputTuple,
      PaymentReceivedEvent.OutputTuple,
      PaymentReceivedEvent.OutputObject
    >;

    "PermitPayment(address,uint256,uint256,uint256)": TypedContractEvent<
      PermitPaymentEvent.InputTuple,
      PermitPaymentEvent.OutputTuple,
      PermitPaymentEvent.OutputObject
    >;
    PermitPayment: TypedContractEvent<
      PermitPaymentEvent.InputTuple,
      PermitPaymentEvent.OutputTuple,
      PermitPaymentEvent.OutputObject
    >;
  };
}
